### ISSUE TITLE
GraphQL-go Logo?

### ISSUE THREAD

**Issue by syrusakbary** [graphql-go/graphql#113]
Hi!
I'm speaking in the [upcoming React.js conference](http://conf.reactjs.com/schedule.html#a-graphql-framework-in-non-js-servers) about GraphQL in different languages, and would be very useful if I have a logo of "GraphQL-go" so I can use it in one of the slides.

Thanks!

**Comment by bbuck** [comment]
I reached out to an artist buddy of mine, but I'm not sure if he's going to be able to do it in the time frame or if he's interested. Thought I'd go ahead an mention it just in case.

**Comment by syrusakbary** [comment]
Great! Just let me know if you have it on time! :wink:

**Comment by sogko** [comment]
Opps, I think we missed the deadline (the conference was 22 - 23 Feb 2016).

Still accepting ideas / contributions!

**Comment by mleonard87** [comment]
Heres some ideas to get something started. Mostly based around gopher having 6 bits sticking out and the GraphQL logo having 6 points and the hot pink color used for GraphQL.

![gopher1sm](https://cloud.githubusercontent.com/assets/1535972/14173680/208bd050-f78b-11e5-9454-dfd64efb1457.png)
GopherQL 1

![gopher2sm](https://cloud.githubusercontent.com/assets/1535972/14173686/2cf8cbea-f78b-11e5-9743-549591d2ee61.png)
GopherQL 2

![gopher3sm](https://cloud.githubusercontent.com/assets/1535972/14173690/318f3d1a-f78b-11e5-8e30-5bb40da8d966.png)
GopherQL 3

![gopher4sm](https://cloud.githubusercontent.com/assets/1535972/14173694/3623a6a4-f78b-11e5-8bee-bc975e7ffff2.png)
GopherQL 4

**Comment by sogko** [comment]
Thanks for sharing your ideas guys, keep it coming! I love it when we see everyone pitching in to help the community 👍

I like how the Gopher slowly "falls" into GraphQL and became one as GopherQL hahaha nifty idea.

There were some discussion on logos in #29 , I'm going to copy some of them over here and make this issue a central place for discussions on the logos and brand identity for this project.

I've also posted a job at [Open Source Design / http://opensourcedesign.net](http://opensourcedesign.net/jobs/jobs/2016-04-02-logo-for-graphql-go). (Pretty cool project, they aim to bring in and encourage designers into contributing to open-source projects)

Keep the feedback and comments coming!
---

@EmergentBehavior contributed his idea here: https://github.com/graphql-go/graphql/issues/29#issuecomment-154103825


---

For inspirations from other implementations:
- [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) (Ruby)
![](https://cloud.githubusercontent.com/assets/2231765/9094460/cb43861e-3b66-11e5-9fbf-71066ff3ab13.png)

- [graphene](https://github.com/graphql-python/graphene) (Python, and their website is pretty impressive http://graphene-python.org)
![](https://camo.githubusercontent.com/04f2156e9ca5d92073997410a3ee3f379c584e20/687474703a2f2f6772617068656e652d707974686f6e2e6f72672f66617669636f6e2e706e67)

- [sangria](https://github.com/sangria-graphql/sangria) (Scala)
![](https://raw.githubusercontent.com/sangria-graphql/sangria-logo/master/sangria-logo.png)

**Comment by bbuck** [comment]
@mleonard87 The only thing I don't like about your concepts is the graph swallowing the gopher, have you tried/thought about having the graph symbols on the gopher instead of having the gopher on the graph? Something akin to octocat's incarnations, except probably significantly more toned down.

**Comment by christianpv** [comment]
I like GopherQL 4.

**Comment by bsr203** [comment]
vote for GopherQL 2

**Comment by sogko** [comment]
Something else that I stumbled upon:

From [Golang Melbourne Meetup](http://www.meetup.com/golang-mel/)
![global_438207534 jpeg](https://cloud.githubusercontent.com/assets/78585/14323265/6a4e3e5a-fc52-11e5-9c48-a12a23db0766.png)

**Comment by bbuck** [comment]
@sogko I actually really like that style better than the standard.

**Comment by mkawia** [comment]
GopherQL 4 !! maybe without the outline ...or with, looks good already.

The feet kind off look like tiny butts ,If you'll excuse my immaturity

**Comment by sogko** [comment]
[`go-twitter`](https://github.com/dghubble/go-twitter)

![https://github.com/dghubble/go-twitter](https://camo.githubusercontent.com/3bb4a8153d6ad6243d9540cbb789df2d74f2130a/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f6467687562626c652f676f706865722d6f6e2d626972642e706e67)

Something way different

**Comment by itanny999** [comment]
Here is something that came to my mind. I merged the word 'GO' into the GraphQL node-like structure.

Merge-LOGO1
![concept-final](https://cloud.githubusercontent.com/assets/1792863/14857438/edd07690-0cb9-11e6-8241-5cc52958d998.png)

Merge-LOGO2
![concept-final-1](https://cloud.githubusercontent.com/assets/1792863/14857485/0d45b648-0cba-11e6-9763-14c400c7e2d5.png)

**Comment by myckyc** [comment]
Hey guys! Just found your request at [Open Source Design](http://opensourcedesign.net/jobs/jobs/2016-04-02-logo-for-graphql-go) Here is my thoughts about your possible logo. Just first iteration based on GraphQL geometry.

![graphql-go-logo-v1-01](https://cloud.githubusercontent.com/assets/13270017/18291541/ee247e18-7490-11e6-821e-481b1857963d.png)
![graphql-go-logo-v1-02](https://cloud.githubusercontent.com/assets/13270017/18291542/ee24f2b2-7490-11e6-8004-7b0b7d3c44d2.png)
![graphql-go-logo-v1-03](https://cloud.githubusercontent.com/assets/13270017/18291543/ee26b598-7490-11e6-974d-76f7c9da6fd5.png)

**Comment by aryzle** [comment]
Please pick GraphQL 4 from @mleonard87 
![image](https://user-images.githubusercontent.com/3059750/31231461-f904dd46-a9b4-11e7-9764-f00142624e05.png)

**Comment by LuisIzarra** [comment]
Hi everyone, I was drawing a little bit and this idea came out, maybe someone who wants to give some feedback or any idea? Vibes and good code! 

![received_484787539301208.jpeg](https://user-images.githubusercontent.com/30215263/120528090-ad067f80-c3a0-11eb-874f-accf4fb74b3c.jpeg)

**Comment by Erioldoesdesign** [comment]
Looks like this issue is still active but can I possibly close the open source design job associated with it? https://opensourcedesign.net/jobs/jobs/2016-04-02-logo-for-graphql-go

if you want to keep it open I suggest you update 😄
