### ISSUE TITLE
how to avoid n + 1 query 

### ISSUE THREAD

**Issue by wangfeipeng** [graphql-go/graphql#296]
my data struct like this：
{
	"data": {
		"customers": [{
			"customerProfile": {
				"nickName": "1"
			},
			"id": 1,
			"sex": 0,
			"status": 1,
			"type": 1
		}, {
			"customerProfile": {
				"nickName": "12"
			},
			"id": 12,
			"sex": 0,
			"status": 1,
			"type": 0
		}]
	}
}
it's a list of customer , but I need to  query  N times to get the customerProfile like this:

![image](https://user-images.githubusercontent.com/17864413/37390522-57c19f1a-27a3-11e8-807d-c1ff0c35e511.png)

it will be  bad when N is a big num , how to avoid this problem

**Comment by sfriedel** [comment]
Hi @wangfeipeng,

in the JS world you'd probably use Facebook's [dataloader](https://github.com/facebook/dataloader) library. Although there are at least 2 implementations of a similar library in Golang, it would not be of much use since in graphql-go all fields are resolved sequentially.

There is a PR for parallel field resolution but the current state of it is somewhat unclear. See #213

**Comment by gburt** [comment]
I believe this issue is a duplicate of #106

**Comment by danielspk** [comment]
Parallel queries to the database does not solve the problem n + 1.
It is necessary to defer resolvers in order execute SQL queries with IN operator. Example: SELECT * FROM posts WHERE user_id IN (?).

Any suggestions?

**Comment by chris-ramon** [comment]
> Parallel queries to the database does not solve the problem n + 1.
> It is necessary to defer resolvers in order execute SQL queries with IN operator. Example: SELECT * FROM posts WHERE user_id IN (?).
> 
> Any suggestions?

Hi @danielspk, thanks for reaching us for a question, that's correct parallel/concurrent queries doesn't solve the n + 1 problem, but parallel/concurrent resolvers + a batching library like [`dataloader`](https://github.com/graph-gophers/dataloader) does, you might want to take a look to this two working examples that solves the n + 1 query problem:
- https://gist.github.com/chris-ramon/e90e245ae79d664ec2f22e4c5682ea3b
- https://github.com/graphql-go/graphql-dataloader-example

**Comment by chris-ramon** [comment]
closing this one since was addressed via: https://github.com/graphql-go/graphql/issues/389

**Comment by limianwang** [comment]
@chris-ramon Thanks for you example. I am wondering (not sure if this is the right place) how would we pass the graphQLArgs to the dataloader?
